### ISSUE TITLE
Horizontal scroll in battlegroundMenu

### ISSUE THREAD

**Issue by auslan** [huguenot412/hots-map-drafter#2]
@huguenot412 Was this intended?

> diff --git a/src/app/battleground/battleground.component.css b/src/app/battleground/battleground.component.css
> index 0d00ff3..2203b3a 100644
> --- a/src/app/battleground/battleground.component.css
> +++ b/src/app/battleground/battleground.component.css
> @@ -40,7 +40,7 @@
>  
>  .battlegroundMenu {
>      height: 300px;
> -    overflow: scroll;
> +    overflow: auto;
>  }
>  
>  .menuItem {

**Comment by huguenot412** [comment]
Good catch. Just fixed it. Thanks!
